<?php
namespace Haroob\Email;
use Illuminate\Support\ServiceProvider;

class HaroobEmailServiceProvider extends ServiceProvider
{
    public function boot(){

        $this->loadRoutesFrom(__DIR__."/routes/web.php");
        $this->loadViewsFrom(__DIR__."/views","haroob");
        $this->loadMigrationsFrom(__DIR__."/database/migrations");
        $this->mergeConfigFrom(__DIR__ . "/config/haroob-email.php","haroob-email");
        //publish the configuration,migrations and views
        $this->publishes([
            __DIR__."/config/haroob-email.php" =>config_path('haroob-email.php'),
            __DIR__.'/views' => resource_path('views/vendor/haroob/'),
            __DIR__.'/database/migrations/' => database_path('migrations'),
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

}
